services:
    app:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: php:8.2-fpm
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-80}:80"
        volumes:
            - "./:/app"
